export default [
  'Early Childhood Education',
  'Anthropology',
  'Dentistry',
  'Respiratory Therapy',
  'Geodetic Engineering',
  'Applied Physics',
  'Criminology',
  'Customs Administration',
  'Aeronautics',
  'Aviation',
  'Interior Design',
  'Behavioral Sciences',
  'Culinary Arts',
  'Religious Studies',
  'Architecture',
  'Manufacturing Engineering',
  'Art Studies',
  'Literature',
  'Public Health',
  'Development Studies',
  'Political Science',
  'Biology',
  'Criminal Justice',
  'Broadcast Media Arts and Studies',
  'Business Economics',
  'Chemistry',
  'Game Development',
  'Communication',
  'Chemical Engineering',
  'Mechanical Engineering',
  'Medicine',
  'Industrial Engineering',
  'Electronics Engineering',
  'Clothing Technology',
  'Entrepreneurship',
  'Language ',
  'Filipino',
  'Science',
  'Social Studies',
  'Mathematics',
  'English',
  'Family Life and Child Development',
  'Radiologic Technology',
  'Culinary Management',
  'Geography',
  'Juris Doctor',
  'Advertising Design',
  'Occupational Therapy',
  'Hospitality Management',
  'Geology',
  'Space Science',
  'Botany',
  'Environmental Science',
  'Materials Engineering',
  'Journalism',
  'Metallurgical Engineering',
  'Supply chain management',
  'Mining Engineering',
  'History',
  'Film',
  'Banking',
  'Operations Management',
  'Theology',
  'Environmental Engineering',
  'Music',
  'Veterinary',
  'Literary and Cultural Studies',
  'Philosophy',
  'Accounting Information Systems',
  'Information Systems',
  'Music Business Management',
  'Cosmetic Science',
  'Philippine Arts',
  'Religious Studies',
  'Astronomy',
  'Sports Science',
  'International Studies',
  'Astrophysics',
  'Special Education',
  'Physical Therapy',
  'Forensic Science',
  'Dance',
  'Behavioral Sciences',
  'Filipinology',
  'Management',
  'Agribusiness Economics',
  'Communication and Media Arts',
  'Maritime Engineering',
  'Maritime Transportation',
  'Pharmacy',
  'E-Sports',
  'Medical Laboratory Science',
  'Philippine Studies',
  'Tourism Management',
  'Theater Arts',
  'Entertainment and Multimedia Computing',
  'Physical Education',
  'Environment and Natural Resources Management',
  'Physics',
  'Food and Service Management',
  'Sociology',
  'Linguistics',
  'Agriculture',
  'Animation',
  'Nutrition and Dietetics',
  'Fine Arts',
  'Food Technology',
  'Home Economics',
  'Technology',
  'Civil Engineering',
  'Electrical Engineering',
  'Information Technology',
  'Computer Science',
  'Creative Writing',
  'Economics',
  'Fashion Design',
  'Psychology',
  'Theater Arts',
  'Social Work',
  'Business Administration',
  'Marketing Management',
  'Ceramic Engineering',
  'Human Resource Development Management',
  'Accountancy',
  'Communication Arts',
  'Forestry',
  'Zoology',
  'Railway Engineering',
  'Biochemistry',
  'Molecular Studies',
  'Dental Medicine',
  'Nursing',
  'Pharmacy ',
  'Public Administration',
  'Maritime Studies',
  'Financial Management',
  'Automotive Technology',
  'Civil Technology',
  'Office Administration',
  'Electrical Technology',
  'Library and Information Science',
  'Real Estate Management',
  'Electronics Technology',
  'Food Service Management Technology',
  'Garments & Fashion Design Technology',
  'Heating, Ventilating, Air-Conditioning and Refrigeration ',
  'Welding and Fabrication Technology',
  'Automotive Servicing',
  'Bread & Pastry Production',
  'Carpentry',
  'Dressmaking',
  'Electrical Installation and Maintenance',
  'Electronic Products Assembly and Servicing',
  'Hairdressing',
  'Information Communication Technology',
  'Transportation Management',
  'Refrigeration & Air-Conditioning',
  'Shielded Metal Arc Welding'
]