export default [
  'ABE International College of Business and Accountancy',
  'Abra Valley Colleges',
  'Adamson University',
  'Agusan del Sur College - Bayugan City',
  'AIE College',
  'Airlink International Aviation School',
  'Aklan Catholic College - Kalibo',
  'Aklan Polytechnic College - Kalibo',
  'Aklan State University',
  'Araullo University',
  'Arellano University',
  'Asian College',
  'Ateneo de Manila University',
  'Aurora Polytechnic College',
  'Aurora State College of Technology',
  'Baao Community College - Baao, Camarines Sur',
  'Bacacay Community College - Bacacay, Albay',
  'Bacolod City College',
  'Bago City College',
  'Baguio Central University',
  'Baguio College of Technology',
  'Balete Community College - Balete, Aklan',
  'Baliuag Polytechnic College',
  'Baliuag University',
  'Baptist Voice Bible College - Lucena, Quezon',
  'Basilan State College - Isabela, Basilan',
  'Bataan Heroes Memorial College - Balanga, Bataan',
  'Bataan Peninsula State University',
  'Bataan State College - Dinalupihan, Bataan',
  'Batan Community College - Batan, Aklan',
  'Batanes State College - Basco, Batanes',
  'Batangas Eastern Colleges - San Juan, Batangas',
  'Batangas State University',
  'Belen B. Francisco Foundation',
  'Benguet State University',
  'Bestlink College of the Philippines',
  'Bicol Christian College of Medicine (Ago Medical and Educational Center) - Legazpi City',
  'Bicol College - Daraga, Albay',
  'Bicol Merchant Marine College - Sorsogon City',
  'Bicol State College of Applied Sciences and Technology',
  'Bicol University',
  'Biliran National Agricultural College - Biliran, Biliran Province',
  'Binalbagan Catholic College - Binalbagan, Negros Occidental',
  'Binangonan Catholic College - Binangonan, Rizal',
  'Bohol Institute of Technology',
  'Bohol Island State University (formerly Central Visayas State College of Agriculture, Forestry and Technology) –',
  'Bohol Northeastern Education Foundation',
  'Bool City Central University - Bool City, Biliran',
  'Brent Hospital and Colleges Inc. - Zamboanga City',
  'Brentwood International School - Naga City',
  'Brokenshire College',
  'Brookfield College - Dasmariñas City, Cavite Campus',
  'BST Grace College - San Fernando, Camarines Sur',
  'Bukidnon State University - Malaybalay City, Bukidnon',
  'Bulacan Agricultural State College - San Idelfonso, Bulacan',
  'Bulacan Polytechnic College',
  'Bulacan State University',
  'Cabucgayan National School of Arts and Trades - Bgy. Bunga, Cabucgayan, Biliran Province',
  'Cagayan de Oro College - Carmen, Cagayan de Oro City',
  'Cagayan State University',
  'Cagayan Technical Institute School of Automotive - Tuguegarao City, Cagayan',
  'Cagayan Valley Computer and Information Technology College, Inc.',
  'Cainta Catholic College - Cainta, Rizal',
  'Calabanga Community College - Calabanga, Camarines Sur',
  'Calamba Doctors\' College - Calamba City',
  'Calauag Central College - Calauag, Quezon Province',
  'Calayan Educational Foundation Inc. - Lucena City',
  'Camarines Norte State College',
  'Camiling Colleges - Camiling, Tarlac',
  'Camo College Incorporated - Pili, Camarines Sur',
  'Canossa Colleges - San Pablo City',
  'CAP College Foundation',
  'Capalonga College - Capalonga, Camarines Norte',
  'Capitol University - Corrales Ext., Cagayan de Oro City',
  'Capiz State University',
  'Caraga State University',
  'Carlos Hilado Memorial State College - Talisay City, Cebu',
  'Cataingan Polytechnic Institute - Cataingan, Masbate',
  'Catanduanes Colleges - Virac',
  'Catanduanes Institute of Technology Foundation Inc. - Virac',
  'Catanduanes State University',
  'Cavite State University',
  'Cavite State University',
  'Cebu Aeronautical Technical School - Salinas Drive, Lahug, Cebu City',
  'Cebu Doctors\' University - Mandaue City',
  'Cebu Eastern College - Cebu City',
  'Cebu Institute of Medicine - Cebu City',
  'Cebu Institute of Technology and University - Cebu City',
  'Cebu International Distance Education College - Cebu City',
  'Cebu Normal University',
  'Cebu Normal University - Balamban',
  'Cebu Roosevelt Memorial Colleges - Bogo City, Cebu',
  'Cebu Technological University (formerly Cebu State College of Science and Technology)',
  'Ceguera Technological Colleges (formerly Ceguera Institute of Science and Technology)',
  'Center for Industrial Technology and Enterprise (CITE) Technical Institute, Inc.',
  'Central Bicol State University of Agriculture',
  'Central Colleges of the North - Tuguegarao City, Cagayan',
  'Central Colleges of the Philippines',
  'Central Luzon College of Science and Technology',
  'Central Luzon Doctors\' Hospital Educational Institution',
  'Central Luzon State University - Munoz City',
  'Central Mindanao University',
  'Central Panay College of Science and Technology - Kalibo, Aklan',
  'Central Philippine Adventist College - Negros Occidental',
  'Central Philippine University - Jaro, Iloilo City',
  'Central Philippines State University - Kabankalan City, Negros Occidental',
  'Centre for International Education (CIE)',
  'Centro Escolar University',
  'Chiang Kai Shek College',
  'Chinese General Hospital Colleges',
  'Christ the King College - Calbayog City',
  'Christ the King College - Gingoog City',
  'Christ the King College de Maranding - Maranding Lala, Lanao del Norte',
  'Christ the King Mission Seminary',
  'Christian Polytechnic Institute of Catanduanes - Virac',
  'Chronicles Institute of Isabela - Ilagan City, Isabela',
  'CIIT (Cosmopolitan International Institute of Technology)',
  'CIIT College of Arts and Technology - Tomas Morato, Quezon City',
  'Citi Global College of Cabuyao (Main Campus)',
  'Citi Global College of Calamba (Annex Campus)',
  'City College of Calamba',
  'City College of Lucena',
  'City College of Naga - Peñafrancia Avenue, Naga City',
  'City of Malabon University',
  'City Technological Institute - Tuguegarao City, Cagayan',
  'Claret College of Isabela - Isabela City',
  'Claret Formation Center - Quezon City',
  'Colegio de Capitolio - Tagum City',
  'Colegio de Dagupan',
  'Colegio de Ilagan - Ilagan City, Isabela',
  'Colegio de la Purisima Concepcion',
  'Colegio de Medaillè Miraculous, Inc. - Subic, Zambales',
  'Colegio de Muntinlupa - Muntinlupa City',
  'Colegio de San Clemente - Angono, Rizal',
  'Colegio de San Francisco Javier - Rizal, Zamboanga del Norte',
  'Colegio de San Gabriel - Arcangel - San Jose del Monte, Bulacan',
  'Colegio de San Jose - Jaro, Iloilo City',
  'Colegio de San Juan de Letran',
  'Colegio de San Lorenzo',
  'Colegio de San Lorenzo Ruiz de Manila - Tacloban City',
  'Colegio de San Lorenzo Ruiz de Manila of Northern Samar Inc - Catarman, Northern Samar',
  'Colegio de San Pascual Baylon - Obando, Bulacan',
  'Colegio de Santa Catalina de Alejandria - Dumaguete City',
  'Colegio de Santo Cristo de Burgos - Sariaya, Quezon',
  'Colegio de Santo Tomas - Recoletos',
  'Colegio de Sta. Teresa de Avila - Novaliches, Quezon City',
  'Colegio del Sagrado Corazon de Jesus - Iloilo City',
  'Colegio ng Lungsod ng Batangas',
  'Colegio San Agustin',
  'College of Arts & Sciences of Asia & the Pacific',
  'College of Business Education Science and Technology - Cauayan City, Isabela',
  'College of Divine Wisdom - Paranaque City',
  'College of Mary Immaculate - Poblacion, Pandi, Bulacan',
  'College of Mt. Carmel - Lolomboy, Bulacan',
  'College of Our Lady of Mercy of Pulilan Foundation, Inc.- Longos, Pulilan, Bulacan',
  'College of Saint Lawrence - Balagtas, Bulacan',
  'College of San Benildo - Rizal',
  'College of St. John-Roxas, De La Salle Supervised',
  'College of Technological Sciences - Cebu City',
  'College of the Holy Spirit',
  'College of the Immaculate Conception, Sumacab Este, Cabanatuan City',
  'Columban College - Olongapo City',
  'Columbus College - Lucena City, Quezon',
  'Comteq Computer and Business College - Olongapo City',
  'Concordia College - Paco',
  'Consolatrix College of Toledo City',
  'Cor Jesu College - Digos City',
  'Core Gateway College - San Jose City, Nueva Ecija',
  'Cotabato State University',
  'Credo Domine College - Tuguegarao City, Cagayan',
  'Daniel B. Peña Memorial College Foundation - Tabaco City, Albay',
  'Daraga Community College - Daraga, Albay',
  'Data Center College of the Philippines - Baguio City Campus',
  'Data Center College of the Philippines - Bangued Branch',
  'Data Center College of the Philippines - Vigan City Branch',
  'Datamex Institute of Computer Technology',
  'Davao Central College Inc. - Davao City',
  'Davao del Norte State College - Panabo City',
  'Davao Doctors\' College - Davao City',
  'Davao Medical School Foundation - Davao City',
  'Davao Oriental State University - Mati City',
  'De La Salle Andres Soriano Memorial College - Toledo City, Cebu',
  'De La Salle Araneta University - Malabon',
  'De La Salle University',
  'De Los Santos College',
  'De Ocampo Memorial College - Nagtahan, Sta. Mesa, Manila',
  'De Paul College - Iloilo City',
  'Dee Hwa Liong College Foundation',
  'Diaz College - Tanjay City, Negros Oriental',
  'Dipolog Medical Center College Foundation - Dipolog City',
  'Divine Word College of Bangued',
  'Divine Word College of Calapan',
  'Divine Word College of Laoag',
  'Divine Word College of Legazpi',
  'Divine Word College of San Jose',
  'Divine Word College of Urdaneta',
  'Divine Word College of Vigan',
  'Divine Word College Seminary - Tagaytay City',
  'Divine Word Mission Seminary - Quezon City',
  'Divine Word University of Tacloban',
  'Dominican College of Iloilo',
  'Dominican College of Sta. Rosa, Laguna',
  'Dominican College of Tarlac',
  'Don Bosco Technical College',
  'Don Honorio Ventura Technological State University',
  'Don Mariano Marcos Memorial State University',
  'Dr. Carlos S. Lanting College - Quezon City',
  'Dr. Emilio B. Espinosa Sr. Memorial State College of Agriculture and Technology - Mandaon, Masbate',
  'Dr. Filemon C. Aguilar Memorial College of Las Piñas',
  'Dr. Yanga\'s Colleges Inc. - Bocaue, Bulacan',
  'East Asia International System College - Cauayan City, Isabela',
  'Easter College, Inc. - Baguio City',
  'Eastern Luzon Colleges - Bambang, Nueva Vizcaya',
  'Eastern Samar State University',
  'Eastern Visayas State University',
  'Eastwoods Professional College - Balanga, Bataan',
  'Eduardo L. Joson Memorial College - Palayan City',
  'Electron College of Technical Education',
  'Educational Systems Technological Institute (ESTI) - Boac, Marinduque',
  'Emilio Aguinaldo College - Manila',
  'Emmanuel College of Plaridel - Plaridel, Bulacan',
  'Enderun Colleges',
  'Entrepreneurs School of Asia - Quezon City',
  'Escuela de Nuestra Señora de La Salette - Dagupan City',
  'Eveland Christian College - San Mateo, Isabela',
  'Far Eastern University',
  'Felix O. Alfelor Sr. Foundation College - Sipocot, Camarines Sur',
  'Fellowship Baptist College -Kabankalan City, Negros Occidental',
  'Fernandez College of Arts and Technology - Baliuag, Bulacan',
  'Filamer Christian University - Roxas Avenue, Roxas City, Capiz',
  'First Asia Institute of Technology and Humanities - Tanauan, Batangas',
  'First City Providential College - City of San Jose Del Monte, Bulacan',
  'Five Star Technical Institute - Tuguegarao City, Cagayan',
  'Florencio L. Vargas College (Main Campus, Bagay Road Campus, and Pengue Campus) - Tuguegarao City, Cagayan',
  'Forbes College - Legazpi City',
  'Foundation University - Dumaguete City',
  'Fr. Saturnino Urios University',
  'Franciscan College of the Immaculate Conception - Baybay City, Leyte',
  'Gallego Foundation Colleges - Cabanatuan City',
  'Garcia College of Technology - Kalibo, Aklan',
  'Gateways Institute of Science and Technology - Cogeo Campus',
  'Gateways Institute of Science and Technology - Fairview Campus',
  'Gateways Institute of Science and Technology - Mandaluyong Campus',
  'Gateways Institute of Science and Technology - Pasig Campus',
  'Gen. Santos Doctors\' Medical School Foundation Inc. - General Santos City',
  'General de Jesus College - San Isidro, Nueva Ecija',
  'Gensantos Foundation College - General Santos City',
  'Global City Innovative College - Bonifacio Global City, Taguig',
  'Global Computer INFOTEQ School, Inc.',
  'Global IT Colleges',
  'Global Reciprocal Colleges - Caloocan',
  'Golden Gate College - Batangas City',
  'Golden Link College Foundation, Inc. - Caloocan',
  'Goldenstate College of General Santos City',
  'Gordon College - Olongapo City',
  'Governor Andres Pascual College - Navotas',
  'Governor Mariano E. Villafuerte Community Colleges',
  'Grace Christian College - Quezon City',
  'Greatways Technical Institute - Makati',
  'Green Valley College Foundation, Inc., City of Koronadal',
  'Greenville College - Pasig',
  'Guagua National Colleges - Guagua, Pampanga',
  'Guimaras State College',
  'Guzman College of Science and Technology - Quiapo, Manila',
  'Holy Angel University - Angeles City',
  'Holy Cross of Davao College',
  'Holy Name University - (formerly Divine Word College of Tagbilaran)',
  'Holy Trinity College - Puerto Princesa City',
  'Hua Siong College of Iloilo',
  'iACADEMY',
  'Ifugao State University - Lamut, Ifugao',
  'IIH College - Novaliches, Quezon City',
  'Iligan Capitol College - Iligan City',
  'Iligan Medical Center College - Iligan City',
  'Ilocos Polytechnic State College',
  'Ilocos Sur Polytechnic State College',
  'Immaculate Concepcion College - Balayan, Batangas',
  'Immaculate Conception International',
  'Immaculate Heart of Mary College',
  'Imus Institute College',
  'Infant Jesus Montessori School College Department - Santiago City',
  'Informatics International College',
  'Information and Communications Technology Academy (iACADEMY)',
  'Infotech Development Systems Colleges (IDS Colleges) - Ligao City',
  'Infotech Institute of Arts and Sciences',
  'Innovative College of Science in Information Technology (ICST) - Bongabong, Oriental Mindoro',
  'Institute of Enterprise Solutions (IES) - Phils, San Jose City, Nueva Ecija',
  'Interface Computer College - Caloocan',
  'Interface Computer College - Cebu',
  'Interface Computer College - Davao',
  'Interface Computer College - Iloilo',
  'Interface Computer College - Manila',
  'Interface Computer College- Cabanatuan',
  'International Academy of Film and Television (IAFT) - Lapu-Lapu City',
  'International Academy of Management and Economics - Makati',
  'International Baptist College (IBC) - Mandaluyong',
  'International Electronics and Technical Institute Inc',
  'International School of Asia and the Pacific - Tuguegarao City, Cagayan',
  'International Technological Institute of Arts and Tourism - Ilagan City, Isabela',
  'Isabela College of Arts and Technology - Cauayan City, Isabela',
  'Isabela Colleges - Cauayan City, Isabela',
  'Isabela Colleges of Science & Technology - Roxas, Isabela',
  'Isabela State University',
  'J.H. Cerilles State College of Zamboanga del Sur',
  'Jake Battaring University Tumauini Campus',
  'Jamiatu Muslim Mindanao - Marawi City',
  'JE Mondejar Computer College - Tacloban City',
  'Jesus Reigns Christian College',
  'John B. Lacson Colleges Foundation - Alijis, Bacolod City',
  'John B. Lacson Foundation Maritime University - Arevalo, Iloilo City',
  'John B. Lacson Foundation Maritime University - Molo, Iloilo City',
  'John Paul College - Davao City',
  'John Paul College - Odiong, Roxas, Oriental Mindoro',
  'John Wesley College - Tuguegarao City, Cagayan',
  'Joji Ilagan Career Center Foundation, Inc. - Davao City and General Santos City',
  'Jose Abad Santos Memorial School Quezon City',
  'Jose C. Feliciano College - Dau, Mabalacat, Pampanga',
  'Jose Maria College - Davao City',
  'Jose Rizal Memorial State University',
  'Jose Rizal University - Mandaluyong',
  'JP Sioson General Hospital and Colleges - Quezon City',
  'Kabankalan Catholic College (KCC) - Kabankalan, Negros Occidental',
  'Kalayaan College - Quezon City',
  'KCI Colleges - Isulan, Sultan Kudarat',
  'Kolehiyo Ng Pantukan (KNP) -Pantukan, Davao de Oro',
  'Kolehiyo ng Subic - Subic, Zambales',
  'La Carlota City College - La Carlota, Negros Occidental',
  'La Concordia College - Paco, Manila',
  'La Consolacion College - 10th Avenue, Caloocan',
  'La Consolacion College - Bacolod',
  'La Consolacion College - Bais City, Negros Oriental',
  'La Consolacion College - Biñan',
  'La Consolacion College - Daet, Camarines Norte',
  'La Consolacion College - Iriga City',
  'La Consolacion College - Liloan, Cebu',
  'La Consolacion College - Mendiola, Manila',
  'La Consolacion College - Novaliches, Caloocan',
  'La Consolacion College - Pasig',
  'La Consolacion College - Tanauan City, Batangas',
  'La Consolacion College - Trento, Agusan del Sur',
  'La Consolacion University Philippines',
  'La Fortuna College - Cabanatuan City',
  'La Salle College Antipolo -Antipolo City',
  'La Salle University-Ozamiz - Ozamiz City',
  'La Union Colleges of Nursing, Arts and Sciences',
  'La Verdad Christian College - Apalit, Pampanga',
  'La Verdad Christian College - Caloocan',
  'Lacson College - Pasay',
  'Laguna Business College - Sta. Rosa, Laguna',
  'Laguna College - San Pablo City',
  'Laguna College of Business and Arts - Calamba City',
  'Laguna Northwestern College - San Pedro, Laguna',
  'Laguna State Polytechnic University',
  'Laguna University - Sta. Cruz, Laguna',
  'Lapu-Lapu City College - Lapu-Lapu City',
  'Las Piñas College - Pilar Village, Almanza, Las Piñas',
  'Lemery Colleges - Lemery, Batangas',
  'Leyte Institute of Technology - Tacloban City',
  'Leyte Normal University - Tacloban City',
  'Lheny Ganda Santos College - Zaragoza, Nueva Ecija',
  'Liceo de Cagayan University - Carmen, Cagayan de Oro City',
  'Liceo de Davao - Tagum City',
  'Liceo del Verbo Divino - Tacloban City (formerly Divine Word University)',
  'LIEMG Language Center - Valenzuela City',
  'Ligao Community College - Ligao City',
  'Lipa City Colleges - Lipa City',
  'Lipa City Public College',
  'Loreto Academy',
  'Lorma College - San Fernando, La Union',
  'Lourdes College - Capistrano St. - Cagayan de Oro City',
  'Loyola College of Culion - Culion, Palawan',
  'Luna Goco Colleges',
  'Lyceum of Alabang (not affiliated with Lyceum of the Philippines University)',
  'Lyceum of Aparri',
  'Lyceum of Cebu - Kalunasan, Cebu City',
  'Lyceum of Makati',
  'Lyceum of Subic Bay - Subic Bay, Zambales',
  'Lyceum of the Philippines University',
  'Lyceum of Tuao - Cagayan',
  'Lyceum-Northwestern University',
  'Maasin City College - Maasin, Southern Leyte',
  'Mabalacat College - Rizal St., Dolores, Mabalacat, Pampanga',
  'Mach Aviatrix Airhostess Institute - Dumaguete City',
  'Mach Aviatrix Flight Institute - Dumaguete City',
  'Magsaysay Memorial College - San Narciso, Zambales',
  'Ma\'had Kutawato College - Campo Muslim, Cotabato City',
  'Maila Rosario College - Tuguegarao City, Cagayan',
  'Malayan Colleges Laguna - Cabuyao City',
  'Mallig Plains Colleges - Mallig, Isabela',
  'Mambog Institute of Technology-Mambog - Pinabacdao, Samar',
  'Mandaue City College - Mandaue City, Cebu',
  'Manila Adventist Medical Center and Colleges - Pasay',
  'Manila Business College - Manila',
  'Manila Central University - Caloocan',
  'Manila Christian Computer Institute for the Deaf College of Technology - San Mateo, Rizal',
  'Manila Tytana Colleges - Pasay',
  'Manuel L. Quezon University - (Manila, Quezon City and Penarrubia, Abra)',
  'Manuel S. Enverga University Foundation - Lucena City, Quezon',
  'Mapua University',
  'Marian College - Ipil, Zamboanga Sibugay Province',
  'Mariano Marcos State University',
  'Marikina Polytechnic College - Marikina',
  'Marinduque Midwest College - Gasan, Marinduque',
  'Marinduque State University',
  'Mariners\' Polytechnic Colleges Foundation',
  'Martinez Colleges, Inc. - Caloocan',
  'Mary Chiles College - Manila',
  'Mary Johnston College of Nursing - Manila',
  'Mary the Queen College (Pampanga) - Guagua, Pampanga',
  'Maryhill College - Lucena City, Quezon',
  'Masbate Colleges - Masbate City',
  'Masters Technological Institute of Mindanao (MTIM) - Iligan City',
  'Mater Dei College - Tubigon, Bohol',
  'MATS College of Technology - Davao City',
  'Maxino College - Dumaguete',
  'Medical Colleges of Northern Philippines - Peñablanca, Cagayan',
  'Medina College Inc',
  'Mendero College - Pagadian City',
  'Meridian International Business, Arts & Technology College (MINT College) - (Taguig, Pasig & Quezon City)',
  'Messiah College - Mandaluyong',
  'Metro Business College (formerly Metro Data Computer College) - Pasay',
  'Metro Dumaguete College - Dumaguete City',
  'Metro Manila College - Kaligayahan, Novaliches, Quezon City',
  'Metropolitan Hospital College of Nursing',
  'Metropolitan School of Science and Technology - Santiago City',
  'Meycauayan College - Bulacan',
  'MFI Technological Institute',
  'Microcity Computer College Foundation, Inc. - Balanga City',
  'Microspan Software Technology, Inc. - Cotabato City',
  'Mind And Integrity College - Cabuyao City',
  'Mindanao Aeronautical Technical School College of Technology - Davao City',
  'Mindanao Autonomous College - Lamitan City, Basilan',
  'Mindanao Kokusai Daigaku (Mindanao International College) - Davao City',
  'Mindanao Medical Foundation College - Davao City',
  'Mindanao Polytechnic College - General Santos City',
  'Mindanao Sanitarium and Hospital College - Iligan City',
  'Mindanao State University',
  'Mindanao University of Science and Technology - Lapasan, Cagayan de Oro City',
  'Mindoro State College of Agriculture and Technology',
  'Miriam College - (Quezon City & Calamba, Laguna)',
  'Misamis Oriental State College of Agriculture and Technology - Claveria, Misamis Oriental',
  'Misamis University',
  'Mondriaan Aura College - Subic Bay',
  'Monkayo College of Arts of Science and Technology (MONCAST)',
  'Montessori Professional College International (MPCI)',
  'Mount Carmel College - Baler, Aurora',
  'Mount Carmel College - Escalante City, Negros Occidental',
  'Mountain Province State Polytechnic College - Bontoc, Mountain Province',
  'Mountain View College - Mt. Nebo, Valencia City, Bukidnon',
  'Mystical Rose College of Science and Technology - Mangatarem, Pangasinan',
  'Naga College Foundation - Naga City',
  'Naga View Adventist College - Naga City',
  'NAMEI Polytechnic Institute - Mandaluyong',
  'National Christian Life College',
  'National College of Business and Arts',
  'National College of Science and Technology - Dasmariñas City, Cavite',
  'National Police College Regional Training School - Cauayan City, Isabela',
  'National Teachers College - Quiapo, Manila',
  'National University',
  'Naval State University',
  'Navotas Polytechnic College',
  'Nazarenus College and Hospital Foundation, Inc. - Bulacan',
  'Negros College - Ayungon, Negros Orienta',
  'Negros Oriental State University',
  'New Era University',
  'North Davao College Tagum Foundation - Tagum City',
  'North Luzon Philippines State College - Candon City, Ilocos Sur',
  'Northeast Luzon Adventist College - Alicia, Isabela',
  'Northeastern College - Santiago City',
  'Northeastern Mindanao Colleges - Surigao City',
  'Northern Cagayan Colleges Foundation - Ballesteros, Cagayan',
  'Northern Christian College - Laoag City',
  'Northern Davao Colleges - Panabo City',
  'Northern Luzon Adventist College - Sison, Pangasinan',
  'Northern Negros State College of Science and Technology',
  'Northern Philippines College for Maritime Science and Technology, Inc.',
  'Northern Samar Colleges - Catarman, Northern Samar',
  'Northern Zambales College - Masinloc, Zambales',
  'Northlink Technological college - Panabo City',
  'Northwest Samar State University',
  'Northwestern University (Philippines) - Laoag City',
  'Northwestern Visayan Colleges - Kalibo, Aklan',
  'Notre Dame - Siena College of Polomolok',
  'Notre Dame of Dadiangas University - General Santos',
  'Notre Dame of Isulan',
  'Notre Dame of Jolo College - Jolo, Sulu',
  'Notre Dame of Kidapawan College',
  'Notre Dame of Marbel University - Koronadal',
  'Notre Dame of Midsayap College - Midsayap, Cotabato',
  'Notre Dame of Tacurong College',
  'Notre Dame University - Cotabato City',
  'Nueva Ecija University of Science and Technology',
  'Nueva Vizcaya State University',
  'Oas Community College - Oas, Albay',
  'Occidental Mindoro State College - San Jose, Occidental Mindoro',
  'Olivarez College',
  'Opol Community College - Opol, Misamis Oriental',
  'Osmeña Colleges - Masbate City',
  'Our Lady of Assumption College',
  'Our Lady of Fatima University',
  'Our Lady of Guadalupe Colleges - Mandaluyong',
  'Our Lady of Lourdes College - Valenzuela City',
  'Our Lady of Manaoag College - Manaoag, Pangasinan',
  'Our Lady of Mercy College - Borongan City',
  'Our Lady of Perpetual Succor College - Marikina',
  'Our Lady of the Pillar College - Cauayan City, Isabela',
  'Our Lady of the Pillar College - San Manuel, Isabela',
  'Pacific InterContinental College (PIC), Inc. - Las Piñas',
  'Palawan State University',
  'Palompon Institute of Technology - Palompon, Leyte',
  'Pamantasan ng Cabuyao - Cabuyao, Laguna',
  'Pamantasan ng Lungsod ng Maynila',
  'Pamantasan ng Lungsod ng Muntinlupa',
  'Pamantasan ng Lungsod ng Pasay',
  'Pamantasan ng Lungsod ng Pasig',
  'Pamantasan ng Lungsod ng San Pablo - San Pablo City, Laguna',
  'Pamantasan ng Lungsod ng Valenzuela',
  'Pamantasan ng Montalban - Montalban, Rizal',
  'Pambansa-Demokratikong Paaralan',
  'Pambayang Kolehiyo ng Mauban - Mauban, Quezon',
  'Pampanga Agricultural College - Magalang, Pampanga',
  'Pampanga Colleges - Macabebe, Pampanga',
  'Panay Technological College - Kalibo, Aklan',
  'Pangasinan State University',
  'Panpacific University - Urdaneta City',
  'Panpacific University North Philippines - Tayug',
  'Partido State University',
  'Pasig Catholic College - Pasig',
  'Passi Trade School - Passi City',
  'Pateros Technological College - Pateros, Metro Manila',
  'Patria Sable Corpus College - Santiago City',
  'PATTS College of Aeronautics',
  'Philippine College of Criminology (PCCr) - Manila',
  'Philippine College of Health Sciences, Inc. - Manila',
  'Philippine College of Technology - Davao City',
  'Philippine International College',
  'Philippine Law Enforcement College - Tuguegarao City, Cagayan',
  'Philippine Merchant Marine Academy - San Narciso, Zambales',
  'Philippine Military Academy - Baguio City',
  'Philippine Nazarene College - La Trinidad, Benguet',
  'Philippine Normal University',
  'Philippine Women\'s University',
  'Pilar College - Zamboanga City',
  'Pines City Colleges - Baguio City',
  'PLT College Inc. - Bayombong, Nueva Vizcaya',
  'PMI Colleges (Philippine Maritime Institute)',
  'Polangui Community College - Polangui, Albay',
  'Polytechnic University of the Philippines',
  'Quezon City Polytechnic University',
  'Rizal College',
  'Rogationist College - Silang, Cavite',
  'Romblon State University ',
  'Saint Louis University',
  'SAN BEDA UNIVERSITY',
  'Technological Institute of the Philippines',
  'Technological University of the Philippines',
  'The Bearer of Light and Wisdom Colleges - Molino, Bacoor City, Cavite',
  'The Bethany Christian Academy - Cabanatuan City, Inc.',
  'Universidad de Manila',
  'University of Baguio',
  'University of Batangas',
  'University of Bohol - (Tagbilaran City)',
  'University of Cagayan Valley (Cagayan Colleges Tuguegarao)',
  'University of Catbalogan City - Samar',
  'University of Cebu',
  'University of Iloilo',
  'University of James Din - Quezon CityUniversity of James Din - Quezon City',
  'University of Luzon - Dagupan',
  'University of Makati',
  'University of Manila',
  'University of Mindanao',
  'University of Negros Occidental - Recoletos',
  'University of Northeastern Philippines - Iriga City',
  'University of Northern Philippines - Vigan, Ilocos Sur',
  'University of Nueva Caceres',
  'University of Pangasinan - Dagupan City',
  'University of Perpetual Help System Dalta',
  'University of Saint Anthony - San Miguel, Iriga City',
  'University of Saint La Salle - Bacolod City',
  'University of San Agustin - Iloilo City',
  'University of San Carlos',
  'University of San Carlos',
  'University of Santo Tomas',
  'University of Southeastern Philippines - Davao City',
  'University of the Assumption - (San Fernando, Pampanga) ',
  'University of the East',
  'University of the Immaculate Conception - Davao City',
  'University of the Philippines',
  'University of the Visayas',
  'Velez College - Cebu City',
  'Virgen Milagrosa University Foundation - San Carlos, Pangasinan',
  'Visayas State University Main Campus - Baybay City, Leyte',
  'West Visayas State University - Lapaz, Iloilo City',
  'Western Leyte College (WLC) - Ormoc City',
  'Xavier University - Ateneo de Cagayan',
  'Zamboanga Peninsula Polytechnic State University - Zamboanga City',
  'Zamboanga del Sur Maritime Institute of Technology - Pagadian City',
  'Zamboanga State College of Marine Sciences and Technology - Zamboanga City',
  'Zamora Memorial College - Bacacay, Albay',
]